### PR TITLE
allow for disabling ready indicator, e.g. when running tests

### PR DESCRIPTION
**Pull request by janusheide**

### CODE REVIEW

**Comment by janusheide** [comment]
We agreed that this should be changed such that the help and ready character can be set with two functions respectively

**Comment by jpihl** [comment]
I would prefer setters for `print_help` and `print_ready_indicator` booleans. 
Like `set_ready_indicator(const std::string& ready_indicator)` and `print_help_on()` and `print_help_off()` or `set_print_help(bool on)`

**Comment by janusheide** [comment]
Closing this implemented in #9

**Comment by jpihl** [comment]
@janusheide Let's also remove the branch, or what?

**Pull request closed without merging**
